apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: helm-flask
    app.kubernetes.io/managed-by: Helm
  name: helm-flask
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: helm-flask
status:
  loadBalancer: {}